name: rey.moen
description: contingency
version: 0.0.1
author: kje67ha1.goluk63n@5nbb1uev.com
language: scala
buildSystem: maven
pipelines:
  pipelines/Bert_BeattyPearl_E_WhiteKeven_Ferry:
    name: Bert_BeattyPearl_E_WhiteKeven_Ferry
    description: null
    author: kje67ha1.goluk63n@5nbb1uev.com
    mode: batch
    language: scala
    createdAt: '2022-12-28 15:23:21'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
