name: nell.maggio
description: Inverse
version: 0.0.1
author: hv5hz1xw.mcklpca5@ejpizsv0.com
language: scala
buildSystem: maven
pipelines:
  pipelines/Mable_DonnellyBill_DollarCecil_Dach:
    name: Mable_DonnellyBill_DollarCecil_Dach
    description: null
    author: hv5hz1xw.mcklpca5@ejpizsv0.com
    mode: batch
    language: scala
    createdAt: '2022-12-28 06:01:11'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
