name: angelic.mosciski
description: customer loyalty
version: 0.0.1
author: uagayzlb.6vsofikk@adha6qld.com
language: scala
buildSystem: maven
pipelines:
  pipelines/Rickey_GislasonTim_BurrMelonie_Upton:
    name: Rickey_GislasonTim_BurrMelonie_Upton
    description: null
    author: uagayzlb.6vsofikk@adha6qld.com
    mode: batch
    language: scala
    createdAt: '2023-01-05 08:08:20'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
