name: stanley.frami
description: actuating
version: 0.0.1
author: prehtmfz.zryszhpd@inlaeyr6.com
language: scala
buildSystem: maven
pipelines:
  pipelines/Dierdre_CollinsJo_KingVashti_Jerde_Jr_:
    name: Dierdre_CollinsJo_KingVashti_Jerde_Jr_
    description: null
    author: prehtmfz.zryszhpd@inlaeyr6.com
    mode: batch
    language: scala
    createdAt: '2022-12-28 09:47:01'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
