name: wilburn.murphy
description: Graphic Interface
version: 0.0.1
author: s4gx7xc7.wcnoggxg@xoesmucw.com
language: scala
buildSystem: maven
pipelines:
  pipelines/Bobby_GreenTom_MorrowXochitl_Koss:
    name: Bobby_GreenTom_MorrowXochitl_Koss
    description: null
    author: s4gx7xc7.wcnoggxg@xoesmucw.com
    mode: batch
    language: scala
    createdAt: '2023-01-05 07:13:45'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
