name: les.buckridge
description: Optional
version: 0.0.1
author: eivxsux3.zrqggkre@yo2jkhuo.com
language: scala
buildSystem: maven
pipelines:
  pipelines/Caleb_KihnCarrie_DababiFletcher_Raynor:
    name: Caleb_KihnCarrie_DababiFletcher_Raynor
    description: null
    author: eivxsux3.zrqggkre@yo2jkhuo.com
    mode: batch
    language: scala
    createdAt: '2022-12-28 20:13:45'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
