name: jeffrey.lakin
description: Re-engineered
version: 0.0.1
author: ltlwi8bq.u2oxljnb@votin0md.com
language: scala
buildSystem: maven
pipelines:
  pipelines/Malcolm_GrahamJustin_Casey_HowellsVince_Kozey_DDS:
    name: Malcolm_GrahamJustin_Casey_HowellsVince_Kozey_DDS
    description: null
    author: ltlwi8bq.u2oxljnb@votin0md.com
    mode: batch
    language: scala
    createdAt: '2022-12-28 08:14:07'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
